const fs=require("fs"),path=require("path"),os=require("os"),cp=require("child_process"),AdmZip=require("adm-zip");
const TMP=path.join(os.tmpdir(),"BuildZip");
const exists=p=>{try{return fs.existsSync(p)}catch{return false}};
const log=(send,type,text)=>send({type,text,time:new Date().toLocaleTimeString()});
function detect(root){const h=f=>exists(path.join(root,f));if(h("android/app/build.gradle")||h("gradlew")||h("gradlew.bat")||h("settings.gradle")||h("settings.gradle.kts"))return"android";if(h("package.json")){try{const p=JSON.parse(fs.readFileSync(path.join(root,"package.json")));if(p.main||p.build||p.devDependencies?.electron||p.scripts?.electron)return"electron";if(p.scripts?.build)return"node"}catch{}}if(fs.readdirSync(root).some(x=>x.endsWith(".csproj")||x.endsWith(".sln")))return"dotnet";if(h("Cargo.toml"))return"rust";if(h("CMakeLists.txt"))return"cmake";if(h("pyproject.toml")||h("setup.py")||h("requirements.txt"))return"python";if(h("index.html"))return"web";return"unknown"}
function run(cmd,args,cwd,send){return new Promise((resolve,reject)=>{log(send,"info","$ "+cmd+" "+args.join(" "));const p=cp.spawn(cmd,args,{cwd,windowsHide:true,shell:false});p.stdout.on("data",d=>log(send,"stdout",d.toString().trim()));p.stderr.on("data",d=>log(send,"stderr",d.toString().trim()));p.on("error",reject);p.on("close",c=>c===0?resolve():reject(new Error(cmd+" завершился с кодом "+c)))})}
async function buildFromZip(zip,target,send){if(!zip||!exists(zip))throw new Error("ZIP-файл не найден.");if(!zip.toLowerCase().endsWith(".zip"))throw new Error("Поддерживается ZIP-проект.");const id=Date.now().toString(36),root=path.join(TMP,id),dist=path.join(root,"dist");fs.mkdirSync(dist,{recursive:true});log(send,"info","Распаковка: "+path.basename(zip));const archive=new AdmZip(zip);
for(const entry of archive.getEntries()){
  const rel=entry.entryName.replace(/\\\\/g,"/");
  if(rel.startsWith("/")||rel.includes("../")||rel.includes("..\\\\")||/^[A-Za-z]:/.test(rel))throw new Error("Небезопасный путь в ZIP: "+entry.entryName);
}
archive.extractAllTo(root,true);let projectRoot=root;const ch=fs.readdirSync(root,{withFileTypes:true});if(ch.length===1&&ch[0].isDirectory())projectRoot=path.join(root,ch[0].name);const detected=detect(projectRoot);log(send,"success","Проект определён как: "+detected);if(target==="auto")target=detected;if(target==="unknown")throw new Error("Не удалось определить тип проекта.");const out=path.join(dist,target);fs.mkdirSync(out,{recursive:true});
if(target==="android"){const gw=process.platform==="win32"?"gradlew.bat":"./gradlew";await run(gw,["assembleRelease"],projectRoot,send);let apk=null;function walk(d){for(const n of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,n.name);if(n.isDirectory())walk(p);else if(n.name.endsWith(".apk"))apk=p}}walk(projectRoot);if(!apk)throw new Error("APK не найден после Gradle build.");fs.copyFileSync(apk,path.join(out,path.basename(apk)))}
else if(target==="electron"){await run(process.platform==="win32"?"npx.cmd":"npx",["electron-builder","--win","--x64","--publish","never"],projectRoot,send);const r=path.join(projectRoot,"dist");if(exists(r))fs.cpSync(r,out,{recursive:true,force:true})}
else if(target==="dotnet"){const proj=fs.readdirSync(projectRoot).find(x=>x.endsWith(".csproj"));if(!proj)throw new Error("CSProj не найден.");await run("dotnet",["publish",proj,"-c","Release","-r","win-x64","--self-contained","true","-o",out],projectRoot,send)}
else if(target==="rust"){await run("cargo",["build","--release"],projectRoot,send);const b=path.join(projectRoot,"target","release");for(const n of fs.readdirSync(b)){if(n.endsWith(".exe"))fs.copyFileSync(path.join(b,n),path.join(out,n))}}
else if(target==="web"||target==="node"){await run(process.platform==="win32"?"npm.cmd":"npm",["install","--no-audit","--no-fund"],projectRoot,send);if(target==="node")await run(process.platform==="win32"?"npm.cmd":"npm",["run","build"],projectRoot,send);fs.cpSync(projectRoot,out,{recursive:true,force:true,filter:s=>!s.includes("node_modules"))}
else if(target==="python"){if(!exists(path.join(projectRoot,"pyproject.toml")))throw new Error("Python packaging требует pyproject.toml.");await run("python",["-m","build"],projectRoot,send);fs.cpSync(path.join(projectRoot,"dist"),out,{recursive:true,force:true})}
else if(target==="cmake"){const b=path.join(projectRoot,"build");fs.mkdirSync(b,{recursive:true});await run("cmake",["-S",projectRoot,"-B",b,"-DCMAKE_BUILD_TYPE=Release"],projectRoot,send);await run("cmake",["--build",b,"--config","Release"],projectRoot,send);fs.cpSync(b,out,{recursive:true,force:true})}
else throw new Error("Для цели "+target+" нет универсального адаптера.");
log(send,"success","Сборка завершена: "+out);return{ok:true,target,detected,output:out}}
module.exports={buildFromZip};